main: com.massivecraft.massivebooks.MassiveBooks
name: mcess
version: 1.0.0_dev
depend: [mcore]
permissions:
# -------------------------------------------- #
# THE REAL NODES
# -------------------------------------------- #
# -------------------------------------------- #
# START NOTATION
# -------------------------------------------- #
# -------------------------------------------- #
# KITS
# -------------------------------------------- #