main: com.massivecraft.massivebooks.MassiveBooks
name: mcess
version: 1.0.0_dev
depend: [mcore]
permissions:
# -------------------------------------------- #
# THE REAL NODES
# -------------------------------------------- #
  massivebooks.book: {description: access book command, default: false}
# -------------------------------------------- #
# START NOTATION
# -------------------------------------------- #
  massivebooks.*:
    default: false
    children:
      massivebooks.book: true
# -------------------------------------------- #
# KITS
# -------------------------------------------- #
  massivebooks.kit.op:
    default: op
    children:
      massivebooks.*: true
  massivebooks.kit.default:
    default: true
    children:
      massivebooks.book: true